import Head from 'next/head'
import MainLayout from '../src/layouts/MainLayout'
import { TiFilter } from "../icons"
import MySwiper from '../src/components/MySwiper'
import axios from 'axios'
import ProductCart from '../src/components/ProductCard'
import useGetUserId from '../hooks/useGetUserId'
import { useDispatch, useSelector } from 'react-redux'
import { ChangeEvent, useEffect } from 'react'
import { server } from '../config/server'
import { Iproduct } from '../interfaces/productInterface'
import { setProducts, filterProducts, setFilterByNameValue } from "../redux/slices/productsReducer"

interface Props {
  products: Iproduct[]
}

const Home = ({products}:Props) => {
  const decodedToken = useGetUserId()

  const dispatch = useDispatch()
  useEffect(()=>{
    dispatch(setProducts({ products }))
    dispatch(filterProducts())
  },[])
  
  const changeFilteredValueHandler = (e:ChangeEvent<HTMLInputElement>) => {
    dispatch(setFilterByNameValue(e.target.value))
    dispatch(filterProducts())
  }

  const { filteredProducts, filterByNameValue } = useSelector((store:any)=>store.products)

  const {user} = useSelector((store:any)=>store.user)
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout title='Discover'>
        <div className='px-4 pb-[90px]'>
          <div className='flex items-center justify-center gap-3 py-4'>
            <input value={filterByNameValue} onChange={changeFilteredValueHandler} type="text" placeholder='Search Product' className='p-2 rounded flex-1 outline-none shadow text-slate-800 placeholder:text-slate-600 font-semibold' />
            <button className='bg-white rounded p-2 shadow'><TiFilter className='text-[24px] text-slate-600'/></button>
          </div>
          <MySwiper/>
          <div className='flex justify-between items-center py-1'>
            <h1 className='font-bold'>New Trend</h1>
            <span className='text-slate-600 text-sm'>View All</span>
          </div>
          <div className='grid grid-cols-1 md:grid-cols-3 gap-4'>
            {filteredProducts?.map((p:Iproduct)=>(
                <ProductCart images={p.images} price={p.price} title={p.name} _id={p._id} key={p._id}/>
            ))}
          </div>
        </div>
      </MainLayout>
    </>
  )
}

export default Home

export async function getServerSideProps(){
  const res = await axios.get(`${server}/api/products`)
  const products:Iproduct[] = res.data
  return {
    props:{
      products
    }
  }
}
